version: 0.2

env:
  variables:
    RESOURCES_DIR: 'aws/resources'
    TF_COMMAND: 'apply' # apply / destroy

phases:
  pre_build:
    commands:
      - terraform fmt -check -diff -recursive ${RESOURCES_DIR}
      - |
        terraform init -input=false -backend=true \
          -backend-config="${RESOURCES_DIR}/terraform.tfbackend" \
          ${RESOURCES_DIR}
      - terraform validate -json ${RESOURCES_DIR}
  build:
    commands:
      - |
        terraform ${TF_COMMAND} \
          -input=false -auto-approve -compact-warnings \
          -var-file="${RESOURCES_DIR}/terraform.tfvars" \
          ${RESOURCES_DIR}
