version: 0.2

env:
  variables:
    RESOURCES_DIR: 'aws/resources'
    TF_ACTION: 'apply' # apply / destroy

phases:
  pre_build:
    commands:
      # Check
      - terraform fmt -check -diff -recursive ${RESOURCES_DIR}

      # Init
      - |
        terraform init -input=false -backend=true \
          -backend-config="${RESOURCES_DIR}/terraform.tfbackend.json" \
          ${RESOURCES_DIR}

      # Validate
      - terraform validate -json ${RESOURCES_DIR}
  build:
    commands:
      # Pull Requests on 'master' -> plan
      # Push/Merge on 'master' -> apply/destroy
      - |
        if expr "${CODEBUILD_WEBHOOK_TRIGGER}" : "pr/*" > /dev/null; then
          terraform plan \
            -input=false -compact-warnings \
            -var-file="${RESOURCES_DIR}/terraform.tfvars.json" \
            ${RESOURCES_DIR}
        else
          terraform ${TF_ACTION} \
            -input=false -auto-approve -compact-warnings \
            -var-file="${RESOURCES_DIR}/terraform.tfvars.json" \
            ${RESOURCES_DIR}
        fi

